### ISSUE TITLE
Readme update:  Explanation of method of interaction with Apple to poll device information

### ISSUE THREAD

**Issue by DaveDaveDaveDave** [PfisterDaniel/node-red-contrib-apple-find-me#10]
I am interested in understating the flow for polling the device information from Apple.  

1) Does the application call an apple API directly from the node-red host, or is there an intermediate server?
2) How does this method avoid the 2FA normally required by Apple?
3) What security (SSL, etc) is being used in the polling of the device information from Apple?

I'm not looking for a detailed explanation, only a basic flow to understand how the Apple credentials are being handled.  I think it would be good to include in the readme.

Thanks!
Great project!

**Comment by PfisterDaniel** [comment]
No, i call no offical  API from Apple. I capture the Links from Apples „Where is“ App.
The Security is ssl and the Node use only http-Requests...

Die Details please look in the source.

Br
Daniel

Am 14.03.2021 um 19:20 schrieb Bort ***@***.***>:

﻿

I am interested in understating the flow for polling the device information from Apple.

  1.  Does the application call an apple API directly from the node-red host, or is there an intermediate server?
  2.  How does this method avoid the 2FA normally required by Apple?
  3.  What security (SSL, etc) is being used in the polling of the device information from Apple?

I'm not looking for a detailed explanation, only a basic flow to understand how the Apple credentials are being handled. I think it would be good to include in the readme.

Thanks!
Great project!
