### ISSUE TITLE
stuck at "Fetching Devices..."

### ISSUE THREAD

**Issue by tribbles3** [PfisterDaniel/node-red-contrib-apple-find-me#15]
Everything was working fine until a couple of days ago. Now my "Locate My Devices (input)" nodes are no longer working and are stuck displaying "Fetching Devices...". I have created new account settings but that did not work. I have multiple apple accounts that I was accessing and now none of them are working. I am able to directly log into my appleID accounts with no problem.

**Comment by acaranta** [comment]
Same here since several hours :/

**Comment by arduino43** [comment]
Same issue

**Comment by RaoulSargent** [comment]
For me:
"find my phone" works ok. (continues to work)
"locate my devices" gets stuck as described. (was previously working)
"send message" failed, statuscode 500  (this has never worked for me)

**Comment by dhanzseros** [comment]
Same here. It stopped working at 2021.05.12. 03:13 GMT+1 :) Anyone knows how to get it work again?

**Comment by PfisterDaniel** [comment]
Yes, i have the same problem but i have a solution for this and i will release a new version today or tomorrow.

**Comment by PfisterDaniel** [comment]
Version 1.1.0 is published

Please test it...

**Comment by RaoulSargent** [comment]
Thank you for the rapid response - upgraded to 1.1.0 (previously on 1.0.9)

"find my phone" works ok. (continues to work)
"locate my devices" works ok. (now working again, only lists 'own' devices as per changelog for 1.1.0)
"send message" failed, statuscode 500 (this has never worked for me)

The send message has never worked for me (1.0.9 and 1.1.0), always gives a 500 error and message "Sending failed, Check your device ID".
I am using the same account and device ID for "Send Message" as being used for the other "Find-Me" nodes, so I know the creds are correct.

Again I want to say thank you for creating these node-red nodes and your continued support.

**Comment by PfisterDaniel** [comment]
Send message works fine for me, I just checked it. Does anyone have the same problem? Unfortunately I can't recreate it on my end. It only works for me when I enter an incorrect DeviceID.
Send message works fine for me, I just checked it

**Comment by RaoulSargent** [comment]
All Working Now - I deleted and re-added everything.
Therefore it is most probably that my problems were my own fault in my config somewhere, but I cannot explain why I see my DeviceID values have now changed compared to what I had previously configured.

So, all working, and thank you again for fixing this so quickly.

Can device IDs change with an iOS upgrade perhaps ?

**Comment by PfisterDaniel** [comment]
This would be possible because I am using a non-official API here that is used by the "Who is" app and can change from one moment to the next. 

A solution for this problem would be to change every 5, 10, 15 ... minutes with the node "Locate my Devices" and store the ID in a variable. Then I point the following nodes to the variable so you could avoid the problem.

**Comment by dhanzseros** [comment]
Hey,

you are awesome! The plugin works fine! Thank you for the quickly fix!!!

Best!

**Comment by acaranta** [comment]
Thank you VERY much for such incredibly quick response :) Works like a charm for my use, as before :)
