### ISSUE TITLE
iPhone 8 not found

### ISSUE THREAD

**Issue by krilor1** [PfisterDaniel/node-red-contrib-apple-find-me#16]
Hello,
Since last update my IPhone 8 is no longer found. iPhone SE still works.

**Comment by RaoulSargent** [comment]
It could be that the Device ID of the iPhone 8 has changed, perhaps following an iOS update.

Use the "Locate My Devices (Input)" node to get a new list of all devices for your AppleID account.
Then check the iPhone 8 to see if it is different to what you were previously using.

**Comment by RaoulSargent** [comment]
I wrote a comment at the end of Issue 14 https://github.com/PfisterDaniel/node-red-contrib-apple-find-me/issues/14 
This may also help when things that were previously working, stop working.

**Comment by PfisterDaniel** [comment]
@RaoulSargent: Great, thx for your support :-D. That's the right answer

**Comment by PfisterDaniel** [comment]
I close this Issue.... If you have more problems please create a new Issue or reopen this...
