### ISSUE TITLE
Family Accounts Missing

### ISSUE THREAD

**Issue by jugicvtj87** [PfisterDaniel/node-red-contrib-apple-find-me#17]
Hey Daniel,

Firstly, awesome work on this add-on. Works much better than an other similar add-on. 
I have just updated to the latest version and my family accounts seem to be missing. Having checked icloud, I can confirm I can still see the family devices online. Let me know if you need any logs etc. 
Node Red Version: v12.18.4
Ubuntu Vmware build: 18.04.1(patched and up to date)

Thanks

Owen

**Comment by Shaquu** [comment]
Hi, latest feature is that family devices are no longer shared. You can thank Apple :)

**Comment by PfisterDaniel** [comment]
@Shaquu Thx for your support :-) Yes, apple has removed family devices from the API. You must use the Account from your family user.
