### ISSUE TITLE
ReferenceError: res is not defined

### ISSUE THREAD

**Issue by Supergiovane** [PfisterDaniel/node-red-contrib-apple-find-me#18]
Hi
Thank you for this great node. It's very useful!
sometime i got this error in the log.
_ReferenceError: res is not defined at checkICloudWithInvervall._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-apple-find-me/nodes/apple-find-me.js:**298:88**)_

All seems to work indeed.
Just to let you know.

**Comment by PfisterDaniel** [comment]
Thx for Report the error. I will check it. Br Daniel

**Comment by PfisterDaniel** [comment]
Fixed with new Version

The new Version is [1.1.3](https://flows.nodered.org/node/node-red-contrib-apple-find-me)

**Comment by Supergiovane** [comment]
Grazie!!!
