### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by opctim** [PfisterDaniel/node-red-contrib-apple-find-me#19]
As a 2FA user i am always notified with an access code after triggering the sound on all my devices. Is there a way around this?

**How about generating a session and storing a token instead of username & password?**

<img width="491" alt="grafik" src="https://user-images.githubusercontent.com/29566085/137314524-a4c56cd4-9efb-4992-9fc9-7b987b92e36b.png">

**Comment by PfisterDaniel** [comment]
Hallo,
ich nutze selbst die 2FA Authentifizierung, doch bei mir erscheint keinerlei Benachrichtigung. Welchen Node verwenden Sie für die Alarmierung des Gerätes?

Ich hab es gerade getestet, weder bei meinem iMac noch bei meinen iPhones wir der Authentifizierungs-Code verlangt.

Könnten Sie evtl. einen ScreenShot Ihres Flows machen?

Gruß Pfister Daniel

**Comment by opctim** [comment]
Hallo,

ich habe das falsche Plugin benutzt, mit deinem funktioniert alles wunderbar, sorry. Issue kann geschlossen werden.
