### ISSUE TITLE
New property request

### ISSUE THREAD

**Issue by Supergiovane** [PfisterDaniel/node-red-contrib-apple-find-me#20]
Hello
again thank you for the great node.
Is it possibile to add a property to allow changing the request's timeout?
I've a machine with a slow internet connection and the node times out without giving any msg output.
Thank you.

**Comment by PfisterDaniel** [comment]
hello, yes should go, I'll take a look at it and publish an update if necessary

**Comment by PfisterDaniel** [comment]
Hi,
i have published a new Version (1.1.2). Please check if solved your problem.
![image](https://user-images.githubusercontent.com/9358627/141660715-95939b2c-7ad0-485b-8204-3137ae8097c2.png)

**Comment by Supergiovane** [comment]
Thank you !!!!!
