### ISSUE TITLE
ReferenceError: res is not defined (different from other reported)

### ISSUE THREAD

**Issue by jspeckman** [PfisterDaniel/node-red-contrib-apple-find-me#22]
Got this error in my logs, would probably not have noticed, except it caused node-red to restart.

Jan 18 09:03:05 clovis-1 node-red[15832]: 18 Jan 09:03:05 - [red] Uncaught Exception:
Jan 18 09:03:05 clovis-1 node-red[15832]: 18 Jan 09:03:05 - [error] ReferenceError: res is not defined
Jan 18 09:03:05 clovis-1 node-red[15832]:     at checkICloudWithPayload._inputCallback (/var/lib/clovis-1/.node-red/node_modules/node-red-contrib-apple-find-me/nodes/apple-find-me.js:562:88)
Jan 18 09:03:05 clovis-1 systemd[1]: node-red.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 09:03:05 clovis-1 systemd[1]: node-red.service: Failed with result 'exit-code'.
Jan 18 09:03:05 clovis-1 systemd[1]: node-red.service: Service hold-off time over, scheduling restart.

Jason

**Comment by PfisterDaniel** [comment]
I've published a new Version with a Bugfix....
I hope this cleared the error.

The new Version is [1.1.3](https://flows.nodered.org/node/node-red-contrib-apple-find-me)
