### ISSUE TITLE
Altitude always zero

### ISSUE THREAD

**Issue by na-am** [PfisterDaniel/node-red-contrib-apple-find-me#23]
I just wanted to implement the altitude in my flows/database but unforunately it's always showing zero in the payload.
two ipads and an iphone showing every time zero. It doesn't matter what type of "positionType" is set (WiFi or GPS).

Besides... the app "node-PAD" https://apps.apple.com/us/app/node-pad/id1534470128 is able to determine the altitude with the integrated location node very precisely:
![image](https://user-images.githubusercontent.com/47410115/170855422-4d66a8fe-0779-4729-a8c6-ec8a550b097a.png)

**Comment by PfisterDaniel** [comment]
Hello,
yes, the altitude is always zero. That's how it comes from Apple. It's the same for me with all my devices iPhone, iPad, Mac's and Apple Watches...

**Comment by na-am** [comment]
thx Daniel, in the meantime i made a workaround with [https://api.opentopodata.org/v1/eudem25m?locations=47,8]
just put lat and lon of the device of your choice into a flow variable in a function node after the "Locate my device" node
[flow_lat_lon_2_alt.txt](https://github.com/PfisterDaniel/node-red-contrib-apple-find-me/files/8805115/flow_lat_lon_2_alt.txt)
:

**Comment by Dunnenj** [comment]
Is it possible to also implement vertical accuracy as it looks like this is not available in the OPEN-ELEVATION API.

**Comment by PfisterDaniel** [comment]
In the next release I added the OpenElevation API and the Altitude is populated. The next release will come in the next few days.

**Comment by PfisterDaniel** [comment]
@Dunnenj 
If I find an API for this that I can use to determine or calculate the vertical accuracy, I will of course also implement this.

**Comment by PfisterDaniel** [comment]
Fixed with release 1.1.8
