### ISSUE TITLE
404 - Not authorised

### ISSUE THREAD

**Issue by zyce78** [PfisterDaniel/node-red-contrib-apple-find-me#24]
Hi

Since yesterday I get 404 - not authorised on my Locate my devices. Tried several accounts. Running NodeRed 3.0.2 and latest Apple find me. No changes made to the system from working to non-working. Anyone else having issues?

Regards
Michael

**Comment by alexpelli** [comment]
Hi... I have same probleme here...
Regards
Alex

**Comment by ChristianSwift** [comment]
Same problem! Apple may has changed service.

**Comment by PfisterDaniel** [comment]
Yes, i have the same problem, but no solution yet. I'm working on it and trying to figure out what's causing it.

**Comment by dhanzseros** [comment]
Hey!

Same to me. I really hope you can figure it out what is the problem. So much thank you!!!! :)

**Comment by edautz** [comment]
Dame probleem here Yesterday after 20:14. Good luck.

**Comment by Qnzvna** [comment]
+1

**Comment by brinkgit** [comment]
Hello,

Same to me, tried different computers and different devices. So probably indeed Apple who changed something.
Started tuesday around 21.15 (Amsterdam time).

Good luck in fixing!

**Comment by zyce78** [comment]
> Yes, i have the same problem, but no solution yet. I'm working on it and trying to figure out what's causing it.

If you need help testing or if I can be of any help let me know.

**Comment by edautz** [comment]
Seems to work again. Changed nothing in the flow, the error is gone and location is determined like before this happened.

**Comment by PfisterDaniel** [comment]
Yes, my flow is working again now. I hope that was just a temporary problem :-)

**Comment by zyce78** [comment]
Mine too! Perfect! Using this for my tracking devices, so quite important for me :) Cheers all!

**Comment by brinkgit** [comment]
Works again! Happy man here!
Happens sometimes more but than for a few minutes. Took very long this time...

**Comment by alexpelli** [comment]
Finally it works again.. that's fantastic...

**Comment by na-am** [comment]
working again
my influxdb has no data from 2022-08-16  20:50:00 until 2022-08-18  22:55:00 UTC+2

**Comment by dhanzseros** [comment]
Yes it works, perfectly.

**Comment by alexpelli** [comment]
Hi.. I have updated to 1.1.7 but it doesn't works again.. I get 404 - not authorized. Do you have same problem?

**Comment by brinkgit** [comment]
Not updated (using 1.1.3), and no problems....

**Comment by alexpelli** [comment]
I have tried to downgrade to 1.1.3 but it doesn't works.. hope Daniel will solve it...

**Comment by edautz** [comment]
> I have tried to downgrade to 1.1.3 but it doesn't works.. hope Daniel will solve it...

Works fine since the problem suddenly disappeared at 18-08.

**Comment by zyce78** [comment]
Still on 1.1.3 and works fine

**Comment by dhanzseros** [comment]
Yes it works, but I did not updated since this problem.

**Comment by PfisterDaniel** [comment]
Hey Guys, i've tested now on my development system. I've installed the new Version 1.1.7 and it works fine, but i must restart my system. Can test it anyone?

Restart is requiered!

thx

**Comment by zyce78** [comment]
Updated to 1.1.7 and restarted my Raspberry completely. Works "fine". Get's all data but the "status" below where it usually is green with status now is red with {} only. No "status". Though it fetches all data fine.

**Comment by PfisterDaniel** [comment]
Ok thk for testing. What is when you a new Node deploy?

**Comment by zyce78** [comment]
It was due to not entering Geo-API. After setting a value here and redeploy it all works fine. I can now see how many devices are found and green status.

**Comment by PfisterDaniel** [comment]
Perfectly :-D

**Comment by mschoenel** [comment]
Wäre es möglich für jeden einzelnen Lokationspunkt einen eigenen Bereich (Radius) in Metern anzugeben?
Bis jetzt ist das ja "nur" global im Note möglich. 
Wäre cool.
