### ISSUE TITLE
Got an JSON ERROR

### ISSUE THREAD

**Issue by mschoenel** [PfisterDaniel/node-red-contrib-apple-find-me#26]
Ich erhalte den folgenden Fehler seit gestern:
Error: JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"), GET https://api.smarthome-development.de/api/v1/get-elevation?locations=50.13885197653563,8.661651002257527&format=json 502 (connected: true, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"server":"openresty","date":"Mon, 12 Sep 2022 10:00:02 GMT","content-type":"text/html","content-length":"154","connection":"keep-alive"}

iPhone und iPad werden dennoch richtig lokalisiert, allerdings die iwatch nicht mehr.....

**Comment by PfisterDaniel** [comment]
Der Server war mein eigener Raspberry Pi.
Musste den Server wieder entfernen, da dieser nicht genug Ressourcen hat um die Request zu verarbeiten.

Wurde somit mit den Release 1.1.8 behoben.
