### ISSUE TITLE
Sicherheit Zugangsdaten

### ISSUE THREAD

**Issue by hannoverRed** [PfisterDaniel/node-red-contrib-apple-find-me#3]
Hallo Daniel,

Wie sicher und wo liegen die Zugangsdaten? Apple id und Passwort?
Lg Jörn

**Comment by PfisterDaniel** [comment]
Hallo, die Zugangsdaten liegen im Memory-Kontext. Sie sind über die Node-Red Credentials verschlüsselt. Diese werden auch nicht mit Exportiert sofern Sie Exports der Nodes oder Flows vornehmen. Gruß Daniel

**Comment by hannoverRed** [comment]
Darf ich fragen wie das mit der 2 Faktor Authentifizierung ist? Wird die nur bei dem ersten Login benötigt oder popt die jedes Mal auf beim benutzen der Node?

**Comment by PfisterDaniel** [comment]
Eigentlich sollte keine 2 FA auftauchen. Diese API funktioniert ohne 2FA.

**Comment by PfisterDaniel** [comment]
> Darf ich fragen wie das mit der 2 Faktor Authentifizierung ist? Wird die nur bei dem ersten Login benötigt oder popt die jedes Mal auf beim benutzen der Node?

Wird diese bei Ihnen angezeigt?

**Comment by hannoverRed** [comment]
Guten Morgen, 
Kann ich noch nicht sagen. Wollte erst wissen wie das mit den Zugangsdaten ist.
Die wollte ich nicht einfach irgendwo eingeben. Teste es heute Vormittag aber

Mit freundlichem Gruß

Jörn Völkening
Podbielskistraße 282
30655 Hannover
Germany

Mobiltelefon: +49 (0) 1567 8515797
eMail: j.voelkening@icloud.com

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Falls Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender
immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by PfisterDaniel** [comment]
Kann ich gut verstehen, aber im Source können Sie ja nachsehen was mit Ihren Daten passiert.
Übrigens ist eine neue Version 1.0.7 draußen, diese habe ich vor ein paar Minuten veröffentlicht. Hier war noch ein Bug bezüglich der DeviceID vorhanden.

**Comment by hannoverRed** [comment]
ne die 2 facto popt nicht auf!!

kann ich fragen wofür genau "payload.iPhone[2].locationInfo.isInaccurate“ ist
und "payload.iPhone[2].locationInfo.isOld“

gibt es irgendwo eine Beschreibung was alles mit der Node geht?

**Comment by PfisterDaniel** [comment]
Sobald positionsType = "WIFI" dann ist isInaccurate = true da die Position nicht genau ist > 65 m. 
IsOld bedeutet das die ermittelte Position nicht aktuell ist.

Leider gibt es keine genau Definition der Werte, da die verwendete API keine Offizielle API von Apple darstellt. Aber ich werde mal eine Doku erstellen bei Gelegenheit.

Aktuell kann man über die Nodes eine Nachricht and das iPhone senden, Find my iPhone auslösen und die Informationen wie Batterie Zustand und Position der Apple-Geräte ermitteln.

**Comment by hannoverRed** [comment]
Was genau kann man mit der Google api machen? Bei Google kommt auch immer der Hinweis das ich die Api Benutzung noch nicht eingeschränkt habe. Kann man rausfinden woher die Anfrage kommt?

DANN noch eine Frage. Die reinfolge der Geräte, bleibt die beim abrufen immer gleich?


Mit freundlichem Gruß

Jörn Völkening
Podbielskistraße 282
30655 Hannover
Germany

Mobiltelefon: +49 (0) 1567 8515797
eMail: j.voelkening@icloud.com

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Falls Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender
immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

> Am 16.12.2020 um 11:21 schrieb Daniel Pfister <notifications@github.com>:
> 
> ﻿
> Sobald positionsType = "WIFI" dann ist isInaccurate = true da die Position nicht genau ist > 65 m.
> IsOld bedeutet das die ermittelte Position nicht aktuell ist.
> 
> Leider gibt es keine genau Definition der Werte, da die verwendete API keine Offizielle API von Apple darstellt. Aber ich werde mal eine Doku erstellen bei Gelegenheit.
> 
> Aktuell kann man über die Nodes eine Nachricht and das iPhone senden, Find my iPhone auslösen und die Informationen wie Batterie Zustand und Position der Apple-Geräte ermitteln.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Mit freundlichem Gruß

Jörn Völkening
Podbielskistraße 282
30655 Hannover
Germany

Mobiltelefon: +49 (0) 1567 8515797
eMail: j.voelkening@icloud.com

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Falls Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender
immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by PfisterDaniel** [comment]
Das mit dem Einschränken der API von Google ist so ne Sache. Wenn Sie das ganze auf einen öffentlichen Server laufen lassen oder Sie privat eine feste IP haben ja. Ansonsten ist das einschränken etwas schwierig. Da gibt es aber genug Meldungen und Beschwerden im Netz zu. Da muss sich Google drum kümmern.

Ich würde Ihnen zu Nutzung der Here-Api raten. Mit der hab ich die besten Erfahrungen gemacht. (Auch bei den Api-Key wird der Key verschlüsselt im Credentials-Store von Node-Red gespeichert)
Die Reihenfolge bleibt immer gleich, zumindest ist das bei mir der Fall bis jetzt. Falls das mal anders sein sollte bitte hier melden dann werde ich die Keys auf die Namen der Geräte fest Tackern.

**Comment by hannoverRed** [comment]
wo genau liegt der unterschied ob ich open steht map nutze oder here-api?

**Comment by PfisterDaniel** [comment]
Goolge ist die genauste. Aber auch die mit den meisten Einschränkungen sprich Request per Stunde oder auch Monat. Im Endeffekt ändert sich aber nur das Object in "currentAddress". Also gibt es keine großen Unterschiede.

**Comment by PfisterDaniel** [comment]
Achso ja OpenStreetmaps hat keine Einschränkung hier wird auch kein Key benötigt. Bei HereMaps gibt es natürlich auch Einschränkungen diese sind auf der [Website ](https://developer.here.com/pricing) erläutert. Aber diese erreicht man eigentlich im Privaten Bereich bei normaler Nutzung nicht.

**Comment by hannoverRed** [comment]
gibt es Probleme bei minütlichen abfrage?

**Comment by PfisterDaniel** [comment]
Ich verwende 5 Minuten, da das ja auch den Akku der Geräte belastet. Bei jeder anfrage wird ein Request an die Geräte gesendet damit diese Ihren Standort ermitteln und an die Api weitergeben. Also Empfohlen ist Minimum 5 Minuten.... Daher auch der Standard. Die Minuten Ermittlung sollte eigentlich raus sie diente nur der Entwicklung. Benutzung auf eigene Verantwortung :-)

**Comment by hannoverRed** [comment]
ah okay und wenn man mal zwischendurch abfragen will nimmt man dann die Input node!

**Comment by PfisterDaniel** [comment]
Richtig erkannt :-)

**Comment by hannoverRed** [comment]
dann sage ich schonmal danke für die super Hilfe.

**Comment by PfisterDaniel** [comment]
Gerne, ich mach damit das Issue zu. Bei weiteren Fragen oder Bugs einfach ein neues öffnen.
