### ISSUE TITLE
Send Message

### ISSUE THREAD

**Issue by MatzeG** [PfisterDaniel/node-red-contrib-apple-find-me#4]
Hallo Herr Pfister,

kann es sein, das die Funktion Send Message derzeit nicht funktioniert? Ich bekomme immer nen Fehler 500

Gruß Mat

**Comment by PfisterDaniel** [comment]
Guten Morgen,

in der Tat, hier hatte sich wohl ein kleiner Käfer eingeschlichen. Hatte ein falsches Feld abgegriffen. Update kommt im laufe des Tages.

Danke für die Info

Gruß Pfister Daniel

**Comment by MatzeG** [comment]
Gute Arbeit - Danke

**Comment by PfisterDaniel** [comment]
Version 1.0.7 ist online.
