### ISSUE TITLE
Locate my Devices (apple-find-me) doesn't return "batteryLevel" and "batteryState" reliably

### ISSUE THREAD

**Issue by steve2211** [PfisterDaniel/node-red-contrib-apple-find-me#5]
Node Red V1.2.5 running on Raspberry Pi.
node-red-contrib-apple-find-me on V1.0.7.

I had the "Locate my Devices"-Node running for a while and the data was being saved to influx db. However after a while the "msg.payload.iPhone[0].batteryLevel" value started to be 0 more and more often. When I redeploy the Node it returns the correct battery Level once and then starts to return 0 again. Let me know if you need more information.

**Comment by PfisterDaniel** [comment]
Hello, unfortunately I cannot replicate the problem. My node has been running for a long time and I always get the correct percentage values back. I save my values in a SQLite database.

**Comment by PfisterDaniel** [comment]
what interval have you set? My interval is 5 minutes.

**Comment by steve2211** [comment]
My interval is set to 15min. I just double checked if the problem has to do with my code or influxDB but a "debug" node connected to the "Locate my devices" node returns zeros as well. But maybe it has something to do with my phone being in airplane mode during the night? As you can see in the picture the first faulty datasets startet to appear before I turned airplane mode on. Then the last dataset for the day was the one from 01:18 and i turned the airplane mode off at 11:40. The first transmission was correct. After that mostly zeros again.
![dataset](https://user-images.githubusercontent.com/57365328/102720140-d3ed5f80-42f2-11eb-873e-674c86f8138e.PNG)

**Comment by steve2211** [comment]
So I turned the interval back to 5min and now everything works fine. No more zeros. For me this solves my Problem so I will close this case.

**Comment by PfisterDaniel** [comment]
Perfect, but I'll double-check the problem in detail over my Christmas vacation. Thank you for your feedback

**Comment by steve2211** [comment]
Let me know if you find something. The 5min interval is draining the battery of my phone faster than i expected ;)
