### ISSUE TITLE
Question: Does Locate my devices (withpayload) pokes devices realtime

### ISSUE THREAD

**Issue by goldriver2** [PfisterDaniel/node-red-contrib-apple-find-me#6]
Do you know if the Locate my devices (withpayload) actually triggers a search of the devices and returns realtime location or if it gets the latest location that the account have for the devices ?

**Comment by PfisterDaniel** [comment]
Hello, yes, the location search is triggered directly (as well as on the Icloud homepage). If the location is available, it will also be returned. If this is not the case, the last known location is returned. You can see the time stamp of the detected location under locationInfo -> locationTimeStamp.

I hope you can understand my english. it's not the best :-D

**Comment by goldriver2** [comment]
Perfect, thanks and your English was perfectly clear. I will manage and work with the "location time stamp" to make sure I provide the correct data
Thanks a lot
