### ISSUE TITLE
Device-ID

### ISSUE THREAD

**Issue by FabrizioTacchino** [PfisterDaniel/node-red-contrib-apple-find-me#7]
Hi Daniel, i tried your script (with nodered, but my Device Id doesn't work) which id should i use of my phone ??

ICCID?
SEID?
(the ID that you read from Itunes device?)
Thacks in advance
Fabrizio

**Comment by FabrizioTacchino** [comment]
ECID
serial number
or UDID...
:-)

**Comment by PfisterDaniel** [comment]
Hello Fabrizio (I think this is your Name :-)

You can get the Device-ID from the node (Locate my Device). An example is available on [Readme.md](https://github.com/PfisterDaniel/node-red-contrib-apple-find-me/blob/master/README.md)

Br Daniel

**Comment by PfisterDaniel** [comment]
Is your problem solved?

**Comment by FabrizioTacchino** [comment]
No my friend i have a lot number and I don’t know wich number I need to use…

Can you help me?

 �

**Comment by FabrizioTacchino** [comment]
Yes my friend!!!!!!!!!!!!!!!!!!
WORK!!!!!!!!!!!!!!!!!!!

**Comment by PfisterDaniel** [comment]
Perfect, thx for the reply. With that I'll close the ticket

**Comment by FabrizioTacchino** [comment]
it work but i receved: error code -1
 whay?

**Comment by FabrizioTacchino** [comment]
4/2/2021, 16:04:00node: 60000ead.55d71
msg.payload : Object
object
status: "failed"
statusCode: -1
message: null

**Comment by FabrizioTacchino** [comment]
but i received the message...

**Comment by PfisterDaniel** [comment]
Did you send a message and your device?

**Comment by PfisterDaniel** [comment]
i just tested it, i don't get an error code ...

{"status":"successfully","statusCode":0,"message":"Sound was played successfully"}

**Comment by PfisterDaniel** [comment]
I think you tried to send something too many times ... Please wait between requests. A time interval of 5 minutes should not be undercut. Is a security feature from Apple so that you cannot start a brute force attack
